#pragma once
#define POSITION clang::annotate("skr-shader", "position")
#define NORMAL clang::annotate("skr-shader", "normal")
#define TANGENT clang::annotate("skr-shader", "tangent")
#define UV0 clang::annotate("skr-shader", "uv0")
#define UV1 clang::annotate("skr-shader", "uv1")
#define UV2 clang::annotate("skr-shader", "uv2")
#define UV3 clang::annotate("skr-shader", "uv3")
#define COLOR clang::annotate("skr-shader", "color")
#define VERTEX_ID clang::annotate("skr-shader", "vertex_id")
#define INSTANCE_ID clang::annotate("skr-shader", "instance_id")
#define IS_FRONTFACE clang::annotate("skr-shader", "is_front_face")
#define VERTEX_SHADER clang::annotate("skr-shader", "vertex")
#define PIXEL_SHADER clang::annotate("skr-shader", "pixel")
