test_target("OSTest")
    set_group("05.tests/base")
    add_deps("SkrBase")
    add_files("os/main.cpp")
    set_exceptions("no-cxx")
    add_rules("PickSharedPCH")

test_target("AlgoTest")
    set_group("05.tests/base")
    add_deps("SkrBase")
    add_files("algo/*.cpp")
    set_exceptions("no-cxx")
    add_rules("PickSharedPCH")

target("ContainersTest")
    set_kind("binary")
    set_group("05.tests/base")
    add_deps("SkrBase")
    add_deps("SkrTestFramework", {public = false})
    add_files("containers/*.cpp")
    set_exceptions("no-cxx")
    add_rules("PickSharedPCH")