 shared_module("SkrInspector", "SKR_INSPECT", engine_version)
    public_dependency("SkrDevCore", engine_version)
    add_rules("c++.unity_build", {batchsize = default_unity_batch})
    add_includedirs("include", {public=true})
    add_files("src/**.cpp")