includes("runtime/xmake.lua")
includes("lightning_storage/xmake.lua")
includes("image_coder/xmake.lua")
includes("scene/xmake.lua")
includes("renderer/xmake.lua")
includes("render_graph/xmake.lua")
includes("imgui/xmake.lua")
-- includes("wasm/xmake.lua")
includes("gainput/xmake.lua")
includes("input_system/xmake.lua")
includes("live2d/xmake.lua")
includes("animation/xmake.lua")
includes("inspector/xmake.lua")
includes("tweak/xmake.lua")