target("SkrSandboxEditor")
    add_rules("qt.widgetapp")
    add_deps("QtAdvancedDocking")
    add_includedirs("include")
    add_files("src/*.cpp") 
    add_files("src/MainWindow.ui")
    add_files("src/MainWindow.h")