target("SkrSketchUpCommon")
    set_kind("phony")
    add_rules("utils.install-libs", { libnames = {"sketchup-sdk-v2024.0.553"} })
    add_includedirs("SketchUp", {public = true})
    add_linkdirs("$(buildir)/$(os)/$(arch)/$(mode)", {public=true})

shared_module("SkrSketchUp", "SKR_SKETCH_UP", engine_version)
    set_exceptions("no-cxx")
    add_deps("SkrSketchUpCommon", {public = true})
    public_dependency("SkrCore", engine_version)
    add_includedirs("include", {public = true})
    add_files("src/build.*.cpp")
    add_links("SketchUpAPI", {public = true})

shared_module("SkrSketchUpLive", "SKR_SKETCH_UP", engine_version)
    set_exceptions("no-cxx")
    add_deps("SkrSketchUpCommon", {public = true})
    public_dependency("SkrCore", engine_version)
    add_includedirs("include", {public = true})
    add_files("src/build.*.cpp")
    add_links("sketchup", {public = true})
    add_linkdirs("libs/$(os)", {public = true})
    add_links("x64-msvcrt-ruby270", {public = true})