add_requires("catch2 v3.4.0")

target("SkrTestFramework")
    set_kind("static")
    set_group("05.tests/framework")
    add_packages("catch2", {public = true, inherit = true})
    add_includedirs("framework/include", {public = true})
    add_files("framework/src/*.cpp")
    add_deps("SkrRT")

includes("ecs/xmake.lua")
includes("fs/xmake.lua")
-- includes("daS/xmake.lua")
includes("module/xmake.lua")
includes("cgpu/xmake.lua")
includes("math/xmake.lua")
includes("platform/xmake.lua")
includes("rtti/xmake.lua")
includes("serde/xmake.lua")
includes("hotfix/xmake.lua")