add_requires("gtest")
add_requires("catch2 v3.4.0")

includes("ecs/xmake.lua")
includes("fs/xmake.lua")
-- includes("daS/xmake.lua")
includes("module/xmake.lua")
includes("cgpu/xmake.lua")
includes("math/xmake.lua")
includes("platform/xmake.lua")
includes("rtti/xmake.lua")
includes("serde/xmake.lua")
includes("hotfix/xmake.lua")