codegen_component("SkrToolCore", { api = "TOOL_CORE", rootdir = "include/SkrToolCore" })
    add_files("include/**.h")
    add_files("include/**.hpp")

shared_module("SkrToolCore", "TOOL_CORE", engine_version)
    set_group("02.tools")
    add_rules("c++.unity_build", {batchsize = default_unity_batch})
    set_pcxxheader("src/pch.hpp")
    add_files("src/**.cpp")
    public_dependency("SkrRT", engine_version)
    add_includedirs("include", {public = true})
    on_config(function (target, opt)
        target:add("defines", "SKR_RESOURCE_PLATFORM=u8\""..target:plat().."\"")
    end)