target("AlgoTest")
    set_kind("binary")
    set_group("05.tests/core")
    library_dependency("SkrBase", engine_version)
    add_deps("SkrTestFramework", {public = false})
    add_files("algo/*.cpp")

target("ContainersTest")
    set_kind("binary")
    set_group("05.tests/core")
    library_dependency("SkrBase", engine_version)
    add_deps("SkrTestFramework", {public = false})
    add_files("containers/*.cpp")

target("JsonTest")
    set_group("05.tests/core")
    set_kind("binary")
    public_dependency("SkrCore", engine_version)
    add_deps("SkrTestFramework", {public = false})
    add_rules("c++.unity_build", {batchsize = default_unity_batch})
    add_files("json/main.cpp")

target("SerdeTest")
    set_group("05.tests/core")
    set_kind("binary")
    public_dependency("SkrCore", engine_version)
    add_deps("SkrTestFramework", {public = false})
    add_rules("c++.unity_build", {batchsize = default_unity_batch})
    add_files("serde/main.cpp")