target("SkrRenderGraph")
    set_group("01.modules")
    add_rules("skr.module", {api = "SKR_RENDER_GRAPH", version = engine_version})
    public_dependency("SkrRT", engine_version)
    add_includedirs("include", {public=true})
    add_files("src/*.cpp")
    add_files("src/graphviz/*.cpp", {unity_ignored = true})
    add_rules("c++.noexception")
    add_rules("c++.unity_build", {batchsize = default_unity_batch_size})