#pragma once
//-------------------------------------------------------------------------------
// -> platform
//      SKR_PLAT_WIN32
//      SKR_PLAT_WIN64
//
// -> architecture
//      SKR_ARCH_X86
//      SKR_ARCH_X86_64
//
//-------------------------------------------------------------------------------

// platform
#ifndef SKR_PLATFORM_WIN32
    #define SKR_PLATFORM_WIN32 0
#endif
#ifndef SKR_PLATFORM_WIN64
    #define SKR_PLATFORM_WIN64 0
#endif

// architecture
#ifndef SKR_ARCH_X86
    #define SKR_ARCH_X86 0
#endif
#ifndef SKR_ARCH_X86_64
    #define SKR_ARCH_X86_64 0
#endif