target("SkrBase")
    set_group("01.modules")
    set_exceptions("no-cxx")
    add_rules("skr.static_module", {api = "SKR_BASE"})
    add_rules("c++.unity_build", {batchsize = default_unity_batch_size})
    add_deps("SkrRoot", "SkrCompileFlags", {public = true})
    add_includedirs("include", {public = true})
    add_files("src/**/build.*.c", "src/**/build.*.cpp")