#define LEMON_VERSION "@PROJECT_VERSION@"
#define LEMON_HAVE_LONG_LONG 1

#define LEMON_HAVE_LP 0
#define LEMON_HAVE_MIP 0
#define LEMON_HAVE_GLPK 0
#define LEMON_HAVE_CPLEX 0
#define LEMON_HAVE_SOPLEX 0
#define LEMON_HAVE_CLP 0
#define LEMON_HAVE_CBC 0

#define _LEMON_CPLEX 1
#define _LEMON_CLP 2
#define _LEMON_GLPK 3
#define _LEMON_SOPLEX 4
#define _LEMON_CBC 5

#define LEMON_DEFAULT_LP _LEMON_@LEMON_DEFAULT_LP@
#define LEMON_DEFAULT_MIP _LEMON_@LEMON_DEFAULT_MIP@

#ifdef _WIN32
#define LEMON_USE_WIN32_THREADS 1
#else
#define LEMON_USE_PTHREAD 1
#endif