target("ISPCTextureCompressor")
    set_group("02.tools")
    set_kind("object")
    set_policy("build.across_targets_in_parallel", false)
    add_rules("utils.ispc")
    add_files("src/**.ispc")

target("SkrTextureCompiler")
    set_group("02.tools")
    add_rules("c++.noexception")
    add_rules("skr.module", {api = "TEXTURE_COMPILER", version = engine_version})
    add_includedirs("include", {public=true})
    public_dependency("SkrTool", engine_version)
    add_deps("ISPCTextureCompressor")
    add_files("src/**.cpp")
