shared_module("SkrGameAICo", "SKR_GAMEAI_CO", engine_version)
    set_group("01.modules")
    public_dependency("SkrRT", engine_version)
    add_rules("c++.unity_build", {batchsize = default_unity_batch_size})
    add_includedirs("include", {public=true})
    add_files("src/**.cpp")