//DO NOT EDIT THIS FILE, IT IS AUTO GENERATED BY CODEGEN
%for header in db.includes:
#include "${header}"
%endfor

#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wimplicitly-unsigned-literal"
#endif