target("CommonMathTest")
    set_group("05.tests")
    set_kind("binary")
    public_dependency("SkrRT", engine_version)
    add_packages("gtest")
    add_files("Common/CommonMath.cpp")
    set_languages("c++17")

target("GraphTest")
    set_group("05.tests")
    set_kind("binary")
    public_dependency("SkrRT", engine_version)
    public_dependency("SkrRenderGraph", engine_version)
    add_packages("gtest")
    add_files("Graph/Graph.cpp")
    set_languages("c++17")