target("SerdeTest")
    set_group("05.tests/base")
    set_kind("binary")
    public_dependency("SkrRT", engine_version)
    add_packages("catch2")
    add_rules("c++.unity_build", {batchsize = default_unity_batch_size})
    add_files("main.cpp")