target("SerdeTest")
    set_group("05.tests/base")
    set_kind("binary")
    public_dependency("SkrRT", engine_version)
    add_packages("gtest")
    add_rules("c++.unity_build", {batchsize = default_unity_batch_size})
    add_files("bitpack.cpp", "binary.cpp", "json.cpp", "main.cpp")