target("threads-test")
    set_kind("binary")
    set_group("05.tests/platform")
    public_dependency("SkrRT", engine_version)
    add_packages("gtest")
    add_files("threads/threads.cpp")
    set_languages("c++17")

target("marl-test")
    set_kind("binary")
    set_group("05.tests/platform")
    public_dependency("SkrRT", engine_version)
    add_packages("gtest")
    add_files("marl-test/**.cpp")
    set_languages("c++17")