target("ThreadsTest")
    set_kind("binary")
    set_group("05.tests/threads")
    public_dependency("SkrRT", engine_version)
    add_deps("SkrTestFramework", {public = false})
    add_files("threads/threads.cpp")

target("ServiceThreadTest")
    set_kind("binary")
    set_group("05.tests/threads")
    public_dependency("SkrRT", engine_version)
    add_deps("SkrTestFramework", {public = false})
    add_files("threads/service_thread.cpp")

target("JobTest")
    set_kind("binary")
    set_group("05.tests/task")
    public_dependency("SkrRT", engine_version)
    add_deps("SkrTestFramework", {public = false})
    add_files("threads/job.cpp")

executable_module("Task2Test", "TASK2_TEST", engine_version)
    set_kind("binary")
    set_group("05.tests/task")
    public_dependency("SkrRT", engine_version)
    add_deps("SkrTestFramework", {public = false})
    add_files("task2/**.cpp")

--[[
target("MarlTest")
    set_kind("binary")
    set_group("05.tests/marl")
    public_dependency("SkrRT", engine_version)
    add_deps("SkrTestFramework", {public = false})
    add_rules("c++.unity_build", {batchsize = default_unity_batch_size})
    add_files("marl-test/**.cpp")
]]--