set(BOOST_SOURCES_DIR ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/boost CACHE STRING INTERNAL FORCE)
set(BOOST_INCLUDES_DIR ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/boost CACHE STRING INTERNAL FORCE)

file(GLOB_RECURSE boost_headers ${BOOST_INCLUDES_DIR}/*.h ${BOOST_INCLUDES_DIR}/*.hpp)

set(BOOST_HEADERS ${boost_headers} CACHE STRING INTERNAL FORCE)