name: windows-build

on: [push, pull_request]

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        arch: [ x64 ]
        cxx: [ cxx20 ]
        toolchain: [ msvc, clang-cl ]

    name: ${{ matrix.toolchain }} + ${{ matrix.cxx }} + ${{ matrix.arch }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      # many thanks to NazaraEngine: https://github.com/NazaraEngine/NazaraEngine
      - name: Get current date as package key
        id: cache_key
        run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT
        shell: bash

      # Force xmake to a specific folder (for cache)
      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - uses: ilammy/msvc-dev-cmd@v1

      # Update xmake repository (in order to have the file that will be cached)
      - name: Update xmake repository
        run: xmake repo --update

      # Fetch xmake dephash
      - name: Retrieve dependencies hash
        id: dep_hash
        run: echo "hash=$(xmake l utils.ci.packageskey)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      # Cache xmake dependencies
      - name: Retrieve cached xmake dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.XMAKE_GLOBALDIR }}\.xmake\packages
          key: Windows-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}-${{ steps.dep_hash.outputs.hash }}-W${{ steps.cache_key.outputs.key }}-15

      # Run setup script
      - name: Set env
        id: env
        run: |
          xmake g -c -v
          xmake l setup.lua -v

      - name: ConfigureDebug
        run: xmake f -m debug --arch=${{ matrix.arch }} --toolchain=${{ matrix.toolchain }} --cxx_version=${{ matrix.cxx }} -c -y -v --project_script=./.github/workflows/ci.project.lua --policies=build.ccache:n
      
      - name: BuildDebug
        if: success() || failure()
        shell: cmd
        run: xmake -y -v
      
      - name: TestDebug
        if: success()
        env:
          TRACY_NO_INVARIANT_CHECK: 1
        run: |
          xmake test -g 05.tests/* -vD ... -d yes
      
      - name: ConfigureRelease
        if: success() || failure()
        shell: cmd
        run: xmake f -m release --arch=${{ matrix.arch }} --toolchain=${{ matrix.toolchain }} --cxx_version=${{ matrix.cxx }} -c -y -v --project_script=./.github/workflows/ci.project.lua --use_profile=disable --policies=build.ccache:n
      
      - name: BuildRelease
        if: success() || failure()
        shell: cmd
        run: xmake -y -v
      
      - name: TestRelease
        if: success()
        env:
          TRACY_NO_INVARIANT_CHECK: 1
        run: |
          xmake run -g 05.tests/* -vD ... -d yes
      
      - name: RemoveBuildDir
        uses: JesseTG/rm@v1.0.3
        with:
          path: build/windows
      
      - name: Shipping
        if: success() || failure()
        shell: cmd
        run: |
          xmake f -c -y -m release --arch=${{ matrix.arch }} --toolchain=${{ matrix.toolchain }} --cxx_version=${{ matrix.cxx }} -c -y -v --project_script=./.github/workflows/ci.project.lua --shipping_one_archive=y --use_profile=disable --policies=build.ccache:n
          xmake -y -v
