name: windows-build

on: [push, pull_request]

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        arch: [ x64 ]
        cxx: [ cxx20 ]
        toolchain: [ msvc, clang-cl ]

    name: ${{ matrix.toolchain }} + ${{ matrix.cxx }} + ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
        
      # Cache xmake dependencies
      - name: Retrieve cached package artifacts
        uses: actions/cache@v3
        with:
          path: |
            .sb
            .pkgs
            .build
          key: Windows-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}

      - name: BuildTools
        if: success() || failure()
        shell: cmd
        run: dotnet run SB tools

      - name: BuildPrograms
        if: success() || failure()
        shell: cmd
        run: dotnet run SB
      
      # - name: TestDebug
      #   if: success()
      #   env:
      #     TRACY_NO_INVARIANT_CHECK: 1
      #   run: |
      #     xmake test -g 05.tests/* -vD ... -d yes
      
      # - name: UploadCompileResults
      #   if: success() || failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-binaries-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}
      #     path: build/windows
      
      # - name: RemoveBuildDir
      #   uses: JesseTG/rm@v1.0.3
      #   with:
      #     path: build/windows