name: ci

on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows-latest, arch: x64, toolchain: msvc, configure: debug }
          - { os: windows-latest, arch: x64, toolchain: msvc, configure: release }
          - { os: windows-latest, arch: x64, toolchain: clang-cl, configure: debug }
          - { os: windows-latest, arch: x64, toolchain: clang-cl, configure: release }
          - { os: macos-latest, arch: arm64, toolchain: clang, configure: debug }
          - { os: macos-latest, arch: arm64, toolchain: clang, configure: release }

    name: ${{ matrix.os }} + ${{ matrix.toolchain }} + ${{ matrix.arch }} + ${{ matrix.configure }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Upgrade LLVM
        if: runner.os == 'Windows'
        run: choco upgrade llvm

      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
        
      - name: Restore cached artifacts
        uses: actions/cache/restore@v3
        with:
          path: |
            .sb
            .pkgs
            .build
          key: Windows-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.configure }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: BuildTools
        if: success() || failure()
        run: dotnet run --configuration Release SB tools release verbose ${{ matrix.toolchain }} sha-depend

      - name: BuildPrograms(${{ matrix.configure }})
        if: success()
        run: dotnet run --configuration Release SB build ${{ matrix.configure }} verbose ${{ matrix.toolchain }} sha-depend
      
      - name: Test(${{ matrix.configure }})
        if: success()
        env:
          TRACY_NO_INVARIANT_CHECK: 1
        run: dotnet run --configuration Release SB test ${{ matrix.configure }} verbose ${{ matrix.toolchain }} sha-depend
      
      - name: Save cached artifacts
        uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            .sb
            .pkgs
            .build
          key: Windows-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.configure }}

      - name: UploadCompileResults
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-binaries-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.configure }}
          path: |
            .build/
            !.build/.deps/
            !.build/.gens/
            !.build/.objs/
            !.build/**/*.exp
            !.build/**/*.ilk
      
      # - name: RemoveBuildDir
      #   uses: JesseTG/rm@v1.0.3
      #   with:
      #     path: build/windows