name: ci

on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            arch: x64
            toolchain: msvc
          - os: windows-latest
            arch: x64
            toolchain: clang-cl
          # MacOS builds
          - os: macos-latest
            arch: arm64
            toolchain: appleclang

    name: ${{ matrix.toolchain }} + ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Upgrade LLVM
        if: runner.os == 'Windows'
        run: choco upgrade llvm

      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
        
      - name: Restore cached artifacts
        uses: actions/cache/restore@v3
        with:
          path: |
            .sb
            .pkgs
            .build
          key: Windows-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.toolchain }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          cache: true

      - name: BuildTools(Debug)
        if: success() || failure()
        run: dotnet run --configuration Release SB tools debug verbose ${{ matrix.toolchain }} sha-depend

      - name: BuildPrograms(Debug)
        if: success() || failure()
        run: dotnet run --configuration Release SB build debug verbose ${{ matrix.toolchain }} sha-depend
      
      - name: Test(Debug)
        if: success() || failure()
        env:
          TRACY_NO_INVARIANT_CHECK: 1
        run: dotnet run --configuration Release SB test verbose ${{ matrix.toolchain }} sha-depend

      - name: BuildTools(Release)
        if: success() || failure()
        run: dotnet run --configuration Release SB tools release verbose ${{ matrix.toolchain }} sha-depend

      - name: BuildPrograms(Release)
        if: success() || failure()
        run: dotnet run --configuration Release SB build release verbose ${{ matrix.toolchain }} sha-depend
      
      - name: Test(Release)
        if: success() || failure()
        env:
          TRACY_NO_INVARIANT_CHECK: 1
        run: dotnet run --configuration Release SB test verbose ${{ matrix.toolchain }} sha-depend
      
      - name: Save cached artifacts
        uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            .sb
            .pkgs
            .build
          key: Windows-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.toolchain }}

      - name: UploadCompileResults
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-binaries-${{ matrix.os }}-${{ matrix.toolchain }}
          path: |
            .build/
            !.build/.deps/
            !.build/.gens/
            !.build/.objs/
            !.build/**/*.exp
            !.build/**/*.ilk
      
      # - name: RemoveBuildDir
      #   uses: JesseTG/rm@v1.0.3
      #   with:
      #     path: build/windows