name: windows-ci

on: [push, pull_request]

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        arch: [ x64 ]
        cxx: [ cxx20 ]
        toolchain: [ msvc, clang-cl ]

    name: ${{ matrix.toolchain }} + ${{ matrix.cxx }} + ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Upgrade LLVM
        run: choco upgrade llvm

      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
        
      # Cache xmake dependencies
      - name: Retrieve cached package artifacts
        uses: actions/cache@v3
        with:
          path: |
            .sb
            .pkgs
            .build
          key: Windows-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}-1

      - name: BuildTools(Debug)
        if: success() || failure()
        shell: cmd
        run: dotnet run --configuration Release SB tools debug verbose ${{ matrix.toolchain }} sha-depend

      - name: BuildPrograms(Debug)
        if: success() || failure()
        shell: cmd
        run: dotnet run --configuration Release SB build debug verbose ${{ matrix.toolchain }} sha-depend
      
      - name: Test(Debug)
        if: success() || failure()
        env:
          TRACY_NO_INVARIANT_CHECK: 1
        run: dotnet run --configuration Release SB test verbose ${{ matrix.toolchain }} sha-depend

      - name: BuildTools(Release)
        if: success() || failure()
        shell: cmd
        run: dotnet run --configuration Release SB tools release verbose ${{ matrix.toolchain }} sha-depend

      - name: BuildPrograms(Release)
        if: success() || failure()
        shell: cmd
        run: dotnet run --configuration Release SB build release verbose ${{ matrix.toolchain }} sha-depend
      
      - name: Test(Release)
        if: success() || failure()
        env:
          TRACY_NO_INVARIANT_CHECK: 1
        run: dotnet run --configuration Release SB test verbose ${{ matrix.toolchain }} sha-depend
      
      - name: UploadCompileResults
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-binaries-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}
          path: .build
      
      # - name: RemoveBuildDir
      #   uses: JesseTG/rm@v1.0.3
      #   with:
      #     path: build/windows